version: "3.8"

services:
  api:
    build: .
    container_name: perpustakaan-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
