version: "3.8"

services:
  api:
    build: .
    container_name: perpustakaan-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    env_file:
      - .env
